### ISSUE TITLE
no implicit conversion of Random into Integer

### ISSUE THREAD

**Issue by garyfeltham** [citypay/citypay-api-client-ruby#2]
ApiKey generate from initialize should generate a new key
     Failure/Error: digest = OpenSSL::HMAC.digest('sha256', @licence_key, message.pack("c*"))

     TypeError:
       no implicit conversion of Random into Integer
     # ./lib/citypay_api_client/models/api_key.rb:43:in `pack'
     # ./lib/citypay_api_client/models/api_key.rb:43:in `generate'
     # ./spec/models/api_key_spec.rb:22:in `block (3 levels) in <top (required)>'

**Comment by garyfeltham** [comment]
found the initialisation process with Random.new(16) was invalid and no unit test, fixed by using `Random.new().bytes(16).bytes` and validated with new unit test
